[project]
name = "plant-diseases-detection"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.141.1",
    "python-dotenv>=1.2.2",
    "python-multipart>=0.0.32",
    "ultralytics>=8.4.117",
    "uvicorn[standard]>=0.52.1",
]
